before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w -extldflags '-static'
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.branch={{.Branch}}
      - -X main.buildDate={{.Date}}
    main: ./swupdate-client.go
    binary: swupdate-client
    flags:
      - -trimpath
      - -mod=readonly

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'
      - '^refactor:'
      - '^style:'
      - Merge pull request
      - Merge branch
      - go mod tidy

release:
  github:
    owner: DatanoiseTV
    name: swupdate-cli
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"