name: CI

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22', 'stable']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: |
        go version
        go mod download
    
    - name: Run tests
      run: |
        go test -v -race -coverprofile=coverage.out
        go tool cover -html=coverage.out -o coverage.html
        go tool cover -func=coverage.out > coverage.txt
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella
    
    - name: Upload coverage reports
      if: matrix.go-version == 'stable'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          coverage.html
          coverage.txt

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
    
    - name: Build
      env:
        CGO_ENABLED: 0
      run: |
        VERSION=$(git describe --tags --always --dirty)
        COMMIT=$(git rev-parse --short HEAD)
        BRANCH=$(git rev-parse --abbrev-ref HEAD)
        BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        go build -v -ldflags="-s -w -extldflags '-static' -X main.version=$VERSION -X main.commit=$COMMIT -X main.branch=$BRANCH -X main.buildDate=$BUILD_DATE" -o swupdate-client swupdate-client.go
    
    - name: Test binary
      run: ./swupdate-client -h

  build-binaries:
    runs-on: ubuntu-latest
    needs: [test, build]
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'
    
    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        BINARY_NAME=swupdate-client
        if [ "$GOOS" = "windows" ]; then
          BINARY_NAME=${BINARY_NAME}.exe
        fi
        VERSION=$(git describe --tags --always --dirty)
        COMMIT=$(git rev-parse --short HEAD)
        BRANCH=$(git rev-parse --abbrev-ref HEAD)
        BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        go build -ldflags="-s -w -extldflags '-static' -X main.version=$VERSION -X main.commit=$COMMIT -X main.branch=$BRANCH -X main.buildDate=$BUILD_DATE" -o ${BINARY_NAME} swupdate-client.go
        
        # Rename binary with platform suffix
        FINAL_NAME=swupdate-client-${GOOS}-${GOARCH}
        if [ "$GOOS" = "windows" ]; then
          FINAL_NAME=${FINAL_NAME}.exe
        fi
        mv ${BINARY_NAME} ${FINAL_NAME}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.goos }}-${{ matrix.goarch }}
        path: swupdate-client-*

  release:
    runs-on: ubuntu-latest
    needs: [test, build, build-binaries]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: binary-*
        merge-multiple: true
    
    - name: Download coverage reports
      uses: actions/download-artifact@v4
      with:
        name: coverage-reports
        path: .
    
    - name: Generate checksums
      run: |
        sha256sum swupdate-client-* > checksums.sha256
        sha512sum swupdate-client-* > checksums.sha512
        md5sum swupdate-client-* > checksums.md5
    
    - name: Generate release tag
      id: tag
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          BRANCH=${GITHUB_REF#refs/heads/}
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          SHORT_SHA=${GITHUB_SHA:0:7}
          echo "tag=${BRANCH}-${TIMESTAMP}-${SHORT_SHA}" >> $GITHUB_OUTPUT
        fi
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        name: Release ${{ steps.tag.outputs.tag }}
        draft: false
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
        files: |
          swupdate-client-*
          checksums.*
          coverage.html
          coverage.txt
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21
    
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=5m --out-format=colored-line-number